// AUTO-GENERATED by scripts/generate-media-manifest.mjs
// Add media under public/projects and run npm run media:manifest.

export type MediaItem = { src: string; label: string; filename: string }
export type MediaGroup = { folder: string; images: MediaItem[]; videos: MediaItem[] }

export const mediaManifest: MediaGroup[] = [
  {
    "folder": "All Day Workwear",
    "images": [
      {
        "src": "/projects/All%20Day%20Workwear/All%20Day%20Workwear%20(1).jpg",
        "label": "All Day Workwear (1)",
        "filename": "All Day Workwear/All Day Workwear (1).jpg"
      },
      {
        "src": "/projects/All%20Day%20Workwear/All%20Day%20Workwear.jpg",
        "label": "All Day Workwear",
        "filename": "All Day Workwear/All Day Workwear.jpg"
      }
    ],
    "videos": []
  },
  {
    "folder": "AUDI",
    "images": [
      {
        "src": "/projects/AUDI/AUDI.jpg",
        "label": "AUDI",
        "filename": "AUDI/AUDI.jpg"
      }
    ],
    "videos": []
  },
  {
    "folder": "Australis Music Group",
    "images": [
      {
        "src": "/projects/Australis%20Music%20Group/Australis%20Music%20Group%20(1).jpg",
        "label": "Australis Music Group (1)",
        "filename": "Australis Music Group/Australis Music Group (1).jpg"
      },
      {
        "src": "/projects/Australis%20Music%20Group/Australis%20Music%20Group%20(2).jpg",
        "label": "Australis Music Group (2)",
        "filename": "Australis Music Group/Australis Music Group (2).jpg"
      },
      {
        "src": "/projects/Australis%20Music%20Group/Australis%20Music%20Group%20(3).jpg",
        "label": "Australis Music Group (3)",
        "filename": "Australis Music Group/Australis Music Group (3).jpg"
      },
      {
        "src": "/projects/Australis%20Music%20Group/Australis%20Music%20Group%20(4).jpg",
        "label": "Australis Music Group (4)",
        "filename": "Australis Music Group/Australis Music Group (4).jpg"
      },
      {
        "src": "/projects/Australis%20Music%20Group/Australis%20Music%20Group.jpg",
        "label": "Australis Music Group",
        "filename": "Australis Music Group/Australis Music Group.jpg"
      }
    ],
    "videos": []
  },
  {
    "folder": "Charlie Hair rollers",
    "images": [
      {
        "src": "/projects/Charlie%20Hair%20rollers/BOF_ads%20+%20vid/BOF_ad-1_landscape.jpg",
        "label": "BOF ad-1 landscape",
        "filename": "Charlie Hair rollers/BOF_ads + vid/BOF_ad-1_landscape.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/BOF_ads%20+%20vid/BOF_ad-1_long.jpg",
        "label": "BOF ad-1 long",
        "filename": "Charlie Hair rollers/BOF_ads + vid/BOF_ad-1_long.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/BOF_ads%20+%20vid/BOF_ad-1.jpg",
        "label": "BOF ad-1",
        "filename": "Charlie Hair rollers/BOF_ads + vid/BOF_ad-1.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/BOF_ads%20+%20vid/BOF_ad-2_landscape.jpg",
        "label": "BOF ad-2 landscape",
        "filename": "Charlie Hair rollers/BOF_ads + vid/BOF_ad-2_landscape.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/BOF_ads%20+%20vid/BOF_ad-2_long.jpg",
        "label": "BOF ad-2 long",
        "filename": "Charlie Hair rollers/BOF_ads + vid/BOF_ad-2_long.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/BOF_ads%20+%20vid/BOF_ad-2.jpg",
        "label": "BOF ad-2",
        "filename": "Charlie Hair rollers/BOF_ads + vid/BOF_ad-2.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/MOF_ads%20+%20vid/MOF_ad-1_landscape.jpg",
        "label": "MOF ad-1 landscape",
        "filename": "Charlie Hair rollers/MOF_ads + vid/MOF_ad-1_landscape.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/MOF_ads%20+%20vid/MOF_ad-1_long.jpg",
        "label": "MOF ad-1 long",
        "filename": "Charlie Hair rollers/MOF_ads + vid/MOF_ad-1_long.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/MOF_ads%20+%20vid/MOF_ad-1.jpg",
        "label": "MOF ad-1",
        "filename": "Charlie Hair rollers/MOF_ads + vid/MOF_ad-1.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/MOF_ads%20+%20vid/MOF_ad-2_landscape.jpg",
        "label": "MOF ad-2 landscape",
        "filename": "Charlie Hair rollers/MOF_ads + vid/MOF_ad-2_landscape.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/MOF_ads%20+%20vid/MOF_ad-2_long.jpg",
        "label": "MOF ad-2 long",
        "filename": "Charlie Hair rollers/MOF_ads + vid/MOF_ad-2_long.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/MOF_ads%20+%20vid/MOF_ad-2.jpg",
        "label": "MOF ad-2",
        "filename": "Charlie Hair rollers/MOF_ads + vid/MOF_ad-2.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/TOF_ads%20+%20vid/TOF_ad_1_landscape.jpg",
        "label": "TOF ad 1 landscape",
        "filename": "Charlie Hair rollers/TOF_ads + vid/TOF_ad_1_landscape.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/TOF_ads%20+%20vid/TOF_ad_1_long.jpg",
        "label": "TOF ad 1 long",
        "filename": "Charlie Hair rollers/TOF_ads + vid/TOF_ad_1_long.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/TOF_ads%20+%20vid/TOF_ad_1.jpg",
        "label": "TOF ad 1",
        "filename": "Charlie Hair rollers/TOF_ads + vid/TOF_ad_1.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/TOF_ads%20+%20vid/TOF_ad_2.jpg",
        "label": "TOF ad 2",
        "filename": "Charlie Hair rollers/TOF_ads + vid/TOF_ad_2.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/TOF_ads%20+%20vid/TOF_ad_3.jpg",
        "label": "TOF ad 3",
        "filename": "Charlie Hair rollers/TOF_ads + vid/TOF_ad_3.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/TOF_ads%20+%20vid/TOF_ad_4_for%20later.jpg",
        "label": "TOF ad 4 for later",
        "filename": "Charlie Hair rollers/TOF_ads + vid/TOF_ad_4_for later.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/TOF_ads%20+%20vid/TOF_ad-2_landscape.jpg",
        "label": "TOF ad-2 landscape",
        "filename": "Charlie Hair rollers/TOF_ads + vid/TOF_ad-2_landscape.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/TOF_ads%20+%20vid/TOF_ad-2_long.jpg",
        "label": "TOF ad-2 long",
        "filename": "Charlie Hair rollers/TOF_ads + vid/TOF_ad-2_long.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/TOF_ads%20+%20vid/TOF_ad-3_landscape.jpg",
        "label": "TOF ad-3 landscape",
        "filename": "Charlie Hair rollers/TOF_ads + vid/TOF_ad-3_landscape.jpg"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/TOF_ads%20+%20vid/TOF_ad-3_long.jpg",
        "label": "TOF ad-3 long",
        "filename": "Charlie Hair rollers/TOF_ads + vid/TOF_ad-3_long.jpg"
      }
    ],
    "videos": [
      {
        "src": "/projects/Charlie%20Hair%20rollers/BOF_ads%20+%20vid/BOF_vid%201.mp4",
        "label": "BOF vid 1",
        "filename": "Charlie Hair rollers/BOF_ads + vid/BOF_vid 1.mp4"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/BOF_ads%20+%20vid/BOF_vid%202.mp4",
        "label": "BOF vid 2",
        "filename": "Charlie Hair rollers/BOF_ads + vid/BOF_vid 2.mp4"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/MOF_ads%20+%20vid/MOF_Mega%20Marylin%20Set.mp4",
        "label": "MOF Mega Marylin Set",
        "filename": "Charlie Hair rollers/MOF_ads + vid/MOF_Mega Marylin Set.mp4"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/MOF_ads%20+%20vid/MOF_video_2.mp4",
        "label": "MOF video 2",
        "filename": "Charlie Hair rollers/MOF_ads + vid/MOF_video_2.mp4"
      },
      {
        "src": "/projects/Charlie%20Hair%20rollers/TOF_ads%20+%20vid/TOF_video%20ad.mp4",
        "label": "TOF video ad",
        "filename": "Charlie Hair rollers/TOF_ads + vid/TOF_video ad.mp4"
      }
    ]
  },
  {
    "folder": "Elemental Studio",
    "images": [
      {
        "src": "/projects/Elemental%20Studio/Elemental%20Studio_Logo+Business%20Cards.jpg",
        "label": "Elemental Studio Logo+Business Cards",
        "filename": "Elemental Studio/Elemental Studio_Logo+Business Cards.jpg"
      }
    ],
    "videos": []
  },
  {
    "folder": "FaceitGraphix",
    "images": [
      {
        "src": "/projects/FaceitGraphix/FaceitGraphix_car%20wrap_new%20branding%20+%20wrap.jpg",
        "label": "FaceitGraphix car wrap new branding + wrap",
        "filename": "FaceitGraphix/FaceitGraphix_car wrap_new branding + wrap.jpg"
      }
    ],
    "videos": []
  },
  {
    "folder": "Hardtuned",
    "images": [
      {
        "src": "/projects/Hardtuned/Fashion_EDM%20(1).jpg",
        "label": "Fashion EDM (1)",
        "filename": "Hardtuned/Fashion_EDM (1).jpg"
      },
      {
        "src": "/projects/Hardtuned/Fashion_EDM%20(2).jpg",
        "label": "Fashion EDM (2)",
        "filename": "Hardtuned/Fashion_EDM (2).jpg"
      },
      {
        "src": "/projects/Hardtuned/Fashion_EDM.jpg",
        "label": "Fashion EDM",
        "filename": "Hardtuned/Fashion_EDM.jpg"
      }
    ],
    "videos": []
  },
  {
    "folder": "Kean Construction group",
    "images": [
      {
        "src": "/projects/Kean%20Construction%20group/KEANE_Design-and-Construction.jpg",
        "label": "KEANE Design-and-Construction",
        "filename": "Kean Construction group/KEANE_Design-and-Construction.jpg"
      },
      {
        "src": "/projects/Kean%20Construction%20group/KEANE_Impact-Fertiliser-Expansion_June.jpg",
        "label": "KEANE Impact-Fertiliser-Expansion June",
        "filename": "Kean Construction group/KEANE_Impact-Fertiliser-Expansion_June.jpg"
      },
      {
        "src": "/projects/Kean%20Construction%20group/KEANE_Impact-Fertilities_1.jpg",
        "label": "KEANE Impact-Fertilities 1",
        "filename": "Kean Construction group/KEANE_Impact-Fertilities_1.jpg"
      },
      {
        "src": "/projects/Kean%20Construction%20group/KEANE_Impact-Fertilities_2.jpg",
        "label": "KEANE Impact-Fertilities 2",
        "filename": "Kean Construction group/KEANE_Impact-Fertilities_2.jpg"
      },
      {
        "src": "/projects/Kean%20Construction%20group/KEANE_keep-operating-while-we-build_May.jpg",
        "label": "KEANE keep-operating-while-we-build May",
        "filename": "Kean Construction group/KEANE_keep-operating-while-we-build_May.jpg"
      },
      {
        "src": "/projects/Kean%20Construction%20group/KEANE_NEW-PROJECT-AWARDS.jpg",
        "label": "KEANE NEW-PROJECT-AWARDS",
        "filename": "Kean Construction group/KEANE_NEW-PROJECT-AWARDS.jpg"
      },
      {
        "src": "/projects/Kean%20Construction%20group/KEANE_organic-posts_June_1.jpg",
        "label": "KEANE organic-posts June 1",
        "filename": "Kean Construction group/KEANE_organic-posts_June_1.jpg"
      },
      {
        "src": "/projects/Kean%20Construction%20group/KEANE_organic-posts_June_2_1.jpg",
        "label": "KEANE organic-posts June 2 1",
        "filename": "Kean Construction group/KEANE_organic-posts_June_2_1.jpg"
      },
      {
        "src": "/projects/Kean%20Construction%20group/KEANE_project-highlights.jpg",
        "label": "KEANE project-highlights",
        "filename": "Kean Construction group/KEANE_project-highlights.jpg"
      }
    ],
    "videos": []
  },
  {
    "folder": "Powertec",
    "images": [
      {
        "src": "/projects/Powertec/Magazine%20ads.jpg",
        "label": "Magazine ads",
        "filename": "Powertec/Magazine ads.jpg"
      },
      {
        "src": "/projects/Powertec/packaging%20(1).jpg",
        "label": "packaging (1)",
        "filename": "Powertec/packaging (1).jpg"
      },
      {
        "src": "/projects/Powertec/packaging.jpg",
        "label": "packaging",
        "filename": "Powertec/packaging.jpg"
      },
      {
        "src": "/projects/Powertec/socials.jpg",
        "label": "socials",
        "filename": "Powertec/socials.jpg"
      },
      {
        "src": "/projects/Powertec/WatchAi%20packaging.jpg",
        "label": "WatchAi packaging",
        "filename": "Powertec/WatchAi packaging.jpg"
      }
    ],
    "videos": [
      {
        "src": "/projects/Powertec/Outback%20Marine_Facebook%20Sales%20Campaign%20(1).mp4",
        "label": "Outback Marine Facebook Sales Campaign (1)",
        "filename": "Powertec/Outback Marine_Facebook Sales Campaign (1).mp4"
      },
      {
        "src": "/projects/Powertec/Outback%20Marine_Facebook%20Sales%20Campaign.mp4",
        "label": "Outback Marine Facebook Sales Campaign",
        "filename": "Powertec/Outback Marine_Facebook Sales Campaign.mp4"
      },
      {
        "src": "/projects/Powertec/Powertec_Traffic%20Facebook%20Campaign.mp4",
        "label": "Powertec Traffic Facebook Campaign",
        "filename": "Powertec/Powertec_Traffic Facebook Campaign.mp4"
      },
      {
        "src": "/projects/Powertec/powertec-awarness-facebook-campaign.mp4",
        "label": "powertec-awarness-facebook-campaign",
        "filename": "Powertec/powertec-awarness-facebook-campaign.mp4"
      },
      {
        "src": "/projects/Powertec/powertec-sales-facebook-campaign.mp4",
        "label": "powertec-sales-facebook-campaign",
        "filename": "Powertec/powertec-sales-facebook-campaign.mp4"
      },
      {
        "src": "/projects/Powertec/WatchAi_Wholesaler%20Campaign.mp4",
        "label": "WatchAi Wholesaler Campaign",
        "filename": "Powertec/WatchAi_Wholesaler Campaign.mp4"
      },
      {
        "src": "/projects/Powertec/watchai-wholesaler-campaign.mp4",
        "label": "watchai-wholesaler-campaign",
        "filename": "Powertec/watchai-wholesaler-campaign.mp4"
      }
    ]
  },
  {
    "folder": "Real Estate",
    "images": [
      {
        "src": "/projects/Real%20Estate/Real%20Estate_ARCADIA%20Project.jpg",
        "label": "Real Estate ARCADIA Project",
        "filename": "Real Estate/Real Estate_ARCADIA Project.jpg"
      },
      {
        "src": "/projects/Real%20Estate/Real%20Estate_REGALIA_Project.jpg",
        "label": "Real Estate REGALIA Project",
        "filename": "Real Estate/Real Estate_REGALIA_Project.jpg"
      }
    ],
    "videos": []
  },
  {
    "folder": "Spinal life",
    "images": [
      {
        "src": "/projects/Spinal%20life/BOF-Leads_WA_Personal-Support-2.2.26_1-remarketing-ad-set_landscape.jpg",
        "label": "BOF-Leads WA Personal-Support-2.2.26 1-remarketing-ad-set landscape",
        "filename": "Spinal life/BOF-Leads_WA_Personal-Support-2.2.26_1-remarketing-ad-set_landscape.jpg"
      },
      {
        "src": "/projects/Spinal%20life/BOF-Leads_WA_Personal-Support-2.2.26_1-remarketing-ad-set_long.jpg",
        "label": "BOF-Leads WA Personal-Support-2.2.26 1-remarketing-ad-set long",
        "filename": "Spinal life/BOF-Leads_WA_Personal-Support-2.2.26_1-remarketing-ad-set_long.jpg"
      },
      {
        "src": "/projects/Spinal%20life/BOF-Leads_WA_Personal-Support-2.2.26_1-remarketing-ad-set.jpg",
        "label": "BOF-Leads WA Personal-Support-2.2.26 1-remarketing-ad-set",
        "filename": "Spinal life/BOF-Leads_WA_Personal-Support-2.2.26_1-remarketing-ad-set.jpg"
      },
      {
        "src": "/projects/Spinal%20life/BOF-Leads_WA_Personal-Support-2.2.26_2-lookalike-ad-set_landscape.jpg",
        "label": "BOF-Leads WA Personal-Support-2.2.26 2-lookalike-ad-set landscape",
        "filename": "Spinal life/BOF-Leads_WA_Personal-Support-2.2.26_2-lookalike-ad-set_landscape.jpg"
      },
      {
        "src": "/projects/Spinal%20life/BOF-Leads_WA_Personal-Support-2.2.26_2-lookalike-ad-set_long.jpg",
        "label": "BOF-Leads WA Personal-Support-2.2.26 2-lookalike-ad-set long",
        "filename": "Spinal life/BOF-Leads_WA_Personal-Support-2.2.26_2-lookalike-ad-set_long.jpg"
      },
      {
        "src": "/projects/Spinal%20life/BOF-Leads_WA_Personal-Support-2.2.26_2-lookalike-ad-set.jpg",
        "label": "BOF-Leads WA Personal-Support-2.2.26 2-lookalike-ad-set",
        "filename": "Spinal life/BOF-Leads_WA_Personal-Support-2.2.26_2-lookalike-ad-set.jpg"
      },
      {
        "src": "/projects/Spinal%20life/TOF_back2work/26016%20Back2Work_v2_square.jpg",
        "label": "26016 Back2Work v2 square",
        "filename": "Spinal life/TOF_back2work/26016 Back2Work_v2_square.jpg"
      },
      {
        "src": "/projects/Spinal%20life/TOF_back2work/26016%20Back2Work_v3_square.jpg",
        "label": "26016 Back2Work v3 square",
        "filename": "Spinal life/TOF_back2work/26016 Back2Work_v3_square.jpg"
      },
      {
        "src": "/projects/Spinal%20life/TOF_back2work/26016-Back2Work_v2_landscape.jpg",
        "label": "26016-Back2Work v2 landscape",
        "filename": "Spinal life/TOF_back2work/26016-Back2Work_v2_landscape.jpg"
      },
      {
        "src": "/projects/Spinal%20life/TOF_back2work/26016-Back2Work_v2_long.jpg",
        "label": "26016-Back2Work v2 long",
        "filename": "Spinal life/TOF_back2work/26016-Back2Work_v2_long.jpg"
      },
      {
        "src": "/projects/Spinal%20life/TOF_back2work/26016-Back2Work_v3_landscape.jpg",
        "label": "26016-Back2Work v3 landscape",
        "filename": "Spinal life/TOF_back2work/26016-Back2Work_v3_landscape.jpg"
      },
      {
        "src": "/projects/Spinal%20life/TOF_back2work/26016-Back2Work_v3_long.jpg",
        "label": "26016-Back2Work v3 long",
        "filename": "Spinal life/TOF_back2work/26016-Back2Work_v3_long.jpg"
      },
      {
        "src": "/projects/Spinal%20life/TOF_back2work/back2work_v1_landscape.jpg",
        "label": "back2work v1 landscape",
        "filename": "Spinal life/TOF_back2work/back2work_v1_landscape.jpg"
      },
      {
        "src": "/projects/Spinal%20life/TOF_back2work/back2work_v1_long.jpg",
        "label": "back2work v1 long",
        "filename": "Spinal life/TOF_back2work/back2work_v1_long.jpg"
      },
      {
        "src": "/projects/Spinal%20life/TOF_back2work/back2work_v1_square.jpg",
        "label": "back2work v1 square",
        "filename": "Spinal life/TOF_back2work/back2work_v1_square.jpg"
      },
      {
        "src": "/projects/Spinal%20life/TOF_back2work/back2work-campaign_BOF_Leads_ad-1.jpg",
        "label": "back2work-campaign BOF Leads ad-1",
        "filename": "Spinal life/TOF_back2work/back2work-campaign_BOF_Leads_ad-1.jpg"
      },
      {
        "src": "/projects/Spinal%20life/TOF_back2work/back2work-campaign_BOF_Leads_ad-2.jpg",
        "label": "back2work-campaign BOF Leads ad-2",
        "filename": "Spinal life/TOF_back2work/back2work-campaign_BOF_Leads_ad-2.jpg"
      }
    ],
    "videos": []
  },
  {
    "folder": "The Brooklyn_Wine & Tapas Bar",
    "images": [
      {
        "src": "/projects/The%20Brooklyn_Wine%20&%20Tapas%20Bar/The%20Brooklyn_Wine%20&%20Tapas%20Bar_Socials.jpg",
        "label": "The Brooklyn Wine & Tapas Bar Socials",
        "filename": "The Brooklyn_Wine & Tapas Bar/The Brooklyn_Wine & Tapas Bar_Socials.jpg"
      }
    ],
    "videos": []
  },
  {
    "folder": "The Sycamore school",
    "images": [
      {
        "src": "/projects/The%20Sycamore%20school/ages-3-4_campaign-refresh_1.jpg",
        "label": "ages-3-4 campaign-refresh 1",
        "filename": "The Sycamore school/ages-3-4_campaign-refresh_1.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/ages-3-4_campaign-refresh_2.jpg",
        "label": "ages-3-4 campaign-refresh 2",
        "filename": "The Sycamore school/ages-3-4_campaign-refresh_2.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/ages-9-10_campaign-refresh_1.jpg",
        "label": "ages-9-10 campaign-refresh 1",
        "filename": "The Sycamore school/ages-9-10_campaign-refresh_1.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/ages-9-10_campaign-refresh_2.jpg",
        "label": "ages-9-10 campaign-refresh 2",
        "filename": "The Sycamore school/ages-9-10_campaign-refresh_2.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/allied-health_landscape.jpg",
        "label": "allied-health landscape",
        "filename": "The Sycamore school/allied-health_landscape.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/allied-health_long.jpg",
        "label": "allied-health long",
        "filename": "The Sycamore school/allied-health_long.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/allied-health.jpg",
        "label": "allied-health",
        "filename": "The Sycamore school/allied-health.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/campaign-1_this-is-Sycamore_1.jpg",
        "label": "campaign-1 this-is-Sycamore 1",
        "filename": "The Sycamore school/campaign-1_this-is-Sycamore_1.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/campaign-1_this-is-Sycamore_2.jpg",
        "label": "campaign-1 this-is-Sycamore 2",
        "filename": "The Sycamore school/campaign-1_this-is-Sycamore_2.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/campaign-1_this-is-Sycamore_3_.jpg",
        "label": "campaign-1 this-is-Sycamore 3",
        "filename": "The Sycamore school/campaign-1_this-is-Sycamore_3_.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/campaign-1_this-is-Sycamore_4.jpg",
        "label": "campaign-1 this-is-Sycamore 4",
        "filename": "The Sycamore school/campaign-1_this-is-Sycamore_4.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/campaign-1_this-is-Sycamore_5_.jpg",
        "label": "campaign-1 this-is-Sycamore 5",
        "filename": "The Sycamore school/campaign-1_this-is-Sycamore_5_.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/families-open-day_landscape.jpg",
        "label": "families-open-day landscape",
        "filename": "The Sycamore school/families-open-day_landscape.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/families-open-day_long.jpg",
        "label": "families-open-day long",
        "filename": "The Sycamore school/families-open-day_long.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/families-open-day.jpg",
        "label": "families-open-day",
        "filename": "The Sycamore school/families-open-day.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/Organic_April/Sycamore_organic_April_1.jpg",
        "label": "Sycamore organic April 1",
        "filename": "The Sycamore school/Organic_April/Sycamore_organic_April_1.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/Organic_April/Sycamore_organic_April_2.jpg",
        "label": "Sycamore organic April 2",
        "filename": "The Sycamore school/Organic_April/Sycamore_organic_April_2.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/Organic_April/Sycamore_organic_April_3.jpg",
        "label": "Sycamore organic April 3",
        "filename": "The Sycamore school/Organic_April/Sycamore_organic_April_3.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/Organic_April/Sycamore_organic_April_4.jpg",
        "label": "Sycamore organic April 4",
        "filename": "The Sycamore school/Organic_April/Sycamore_organic_April_4.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/Organic_April/Sycamore_organic_April_5.jpg",
        "label": "Sycamore organic April 5",
        "filename": "The Sycamore school/Organic_April/Sycamore_organic_April_5.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/Organic_April/Sycamore_organic_April_6.jpg",
        "label": "Sycamore organic April 6",
        "filename": "The Sycamore school/Organic_April/Sycamore_organic_April_6.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/Organic_April/Sycamore_organic_April_7.jpg",
        "label": "Sycamore organic April 7",
        "filename": "The Sycamore school/Organic_April/Sycamore_organic_April_7.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/Organic_April/Sycamore_organic_April_8.jpg",
        "label": "Sycamore organic April 8",
        "filename": "The Sycamore school/Organic_April/Sycamore_organic_April_8.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/school-and-early-childhood_landscape.jpg",
        "label": "school-and-early-childhood landscape",
        "filename": "The Sycamore school/school-and-early-childhood_landscape.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/school-and-early-childhood_long.jpg",
        "label": "school-and-early-childhood long",
        "filename": "The Sycamore school/school-and-early-childhood_long.jpg"
      },
      {
        "src": "/projects/The%20Sycamore%20school/school-and-early-childhood.jpg",
        "label": "school-and-early-childhood",
        "filename": "The Sycamore school/school-and-early-childhood.jpg"
      }
    ],
    "videos": [
      {
        "src": "/projects/The%20Sycamore%20school/Campaign%201_this%20is%20Sycamore.mp4",
        "label": "Campaign 1 this is Sycamore",
        "filename": "The Sycamore school/Campaign 1_this is Sycamore.mp4"
      }
    ]
  },
  {
    "folder": "UN",
    "images": [
      {
        "src": "/projects/UN/United%20Nations_Covid19%20Campaign%20(1).jpg",
        "label": "United Nations Covid19 Campaign (1)",
        "filename": "UN/United Nations_Covid19 Campaign (1).jpg"
      },
      {
        "src": "/projects/UN/United%20Nations_Covid19%20Campaign%20(2).jpg",
        "label": "United Nations Covid19 Campaign (2)",
        "filename": "UN/United Nations_Covid19 Campaign (2).jpg"
      },
      {
        "src": "/projects/UN/United%20Nations_Covid19%20Campaign.jpg",
        "label": "United Nations Covid19 Campaign",
        "filename": "UN/United Nations_Covid19 Campaign.jpg"
      }
    ],
    "videos": []
  },
  {
    "folder": "Vetner",
    "images": [
      {
        "src": "/projects/Vetner/BOF_ladder-remarketing_carousel_June_refresh_1.jpg",
        "label": "BOF ladder-remarketing carousel June refresh 1",
        "filename": "Vetner/BOF_ladder-remarketing_carousel_June_refresh_1.jpg"
      },
      {
        "src": "/projects/Vetner/BOF_ladder-remarketing_carousel_June_refresh_2.jpg",
        "label": "BOF ladder-remarketing carousel June refresh 2",
        "filename": "Vetner/BOF_ladder-remarketing_carousel_June_refresh_2.jpg"
      },
      {
        "src": "/projects/Vetner/BOF_ladder-remarketing_carousel_June_refresh_3.jpg",
        "label": "BOF ladder-remarketing carousel June refresh 3",
        "filename": "Vetner/BOF_ladder-remarketing_carousel_June_refresh_3.jpg"
      },
      {
        "src": "/projects/Vetner/BOF_ladder-remarketing_carousel_June_refresh_4.jpg",
        "label": "BOF ladder-remarketing carousel June refresh 4",
        "filename": "Vetner/BOF_ladder-remarketing_carousel_June_refresh_4.jpg"
      },
      {
        "src": "/projects/Vetner/BOF_ladder-remarketing_carousel_June_refresh_5.jpg",
        "label": "BOF ladder-remarketing carousel June refresh 5",
        "filename": "Vetner/BOF_ladder-remarketing_carousel_June_refresh_5.jpg"
      },
      {
        "src": "/projects/Vetner/BOF_ladder-remarketing_carousel_June_refresh_6.jpg",
        "label": "BOF ladder-remarketing carousel June refresh 6",
        "filename": "Vetner/BOF_ladder-remarketing_carousel_June_refresh_6.jpg"
      },
      {
        "src": "/projects/Vetner/BOF_ladder-remarketing_carousel_June_refresh_7.jpg",
        "label": "BOF ladder-remarketing carousel June refresh 7",
        "filename": "Vetner/BOF_ladder-remarketing_carousel_June_refresh_7.jpg"
      },
      {
        "src": "/projects/Vetner/Cargo-Nets_1_landscape.jpg",
        "label": "Cargo-Nets 1 landscape",
        "filename": "Vetner/Cargo-Nets_1_landscape.jpg"
      },
      {
        "src": "/projects/Vetner/Cargo-Nets_1_long.jpg",
        "label": "Cargo-Nets 1 long",
        "filename": "Vetner/Cargo-Nets_1_long.jpg"
      },
      {
        "src": "/projects/Vetner/Cargo-Nets_1.jpg",
        "label": "Cargo-Nets 1",
        "filename": "Vetner/Cargo-Nets_1.jpg"
      },
      {
        "src": "/projects/Vetner/Cargo-Nets_2_landscape.jpg",
        "label": "Cargo-Nets 2 landscape",
        "filename": "Vetner/Cargo-Nets_2_landscape.jpg"
      },
      {
        "src": "/projects/Vetner/Cargo-Nets_2_long.jpg",
        "label": "Cargo-Nets 2 long",
        "filename": "Vetner/Cargo-Nets_2_long.jpg"
      },
      {
        "src": "/projects/Vetner/Cargo-Nets_2.jpg",
        "label": "Cargo-Nets 2",
        "filename": "Vetner/Cargo-Nets_2.jpg"
      },
      {
        "src": "/projects/Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-1_landscape.jpg",
        "label": "PVTL Concreters Traffic remarketing-1 landscape",
        "filename": "Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-1_landscape.jpg"
      },
      {
        "src": "/projects/Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-1_long.jpg",
        "label": "PVTL Concreters Traffic remarketing-1 long",
        "filename": "Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-1_long.jpg"
      },
      {
        "src": "/projects/Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-1.jpg",
        "label": "PVTL Concreters Traffic remarketing-1",
        "filename": "Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-1.jpg"
      },
      {
        "src": "/projects/Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-2_landscape.jpg",
        "label": "PVTL Concreters Traffic remarketing-2 landscape",
        "filename": "Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-2_landscape.jpg"
      },
      {
        "src": "/projects/Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-2_long.jpg",
        "label": "PVTL Concreters Traffic remarketing-2 long",
        "filename": "Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-2_long.jpg"
      },
      {
        "src": "/projects/Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-2.jpg",
        "label": "PVTL Concreters Traffic remarketing-2",
        "filename": "Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-2.jpg"
      },
      {
        "src": "/projects/Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-3_landscape.jpg",
        "label": "PVTL Concreters Traffic remarketing-3 landscape",
        "filename": "Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-3_landscape.jpg"
      },
      {
        "src": "/projects/Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-3_long.jpg",
        "label": "PVTL Concreters Traffic remarketing-3 long",
        "filename": "Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-3_long.jpg"
      },
      {
        "src": "/projects/Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-3.jpg",
        "label": "PVTL Concreters Traffic remarketing-3",
        "filename": "Vetner/remarketing/PVTL_Concreters_Traffic_remarketing-3.jpg"
      },
      {
        "src": "/projects/Vetner/Vetner_organic-posts_April_1.jpg",
        "label": "Vetner organic-posts April 1",
        "filename": "Vetner/Vetner_organic-posts_April_1.jpg"
      },
      {
        "src": "/projects/Vetner/Vetner_organic-posts_April_2.jpg",
        "label": "Vetner organic-posts April 2",
        "filename": "Vetner/Vetner_organic-posts_April_2.jpg"
      },
      {
        "src": "/projects/Vetner/Vetner_organic-posts_April_3.jpg",
        "label": "Vetner organic-posts April 3",
        "filename": "Vetner/Vetner_organic-posts_April_3.jpg"
      },
      {
        "src": "/projects/Vetner/Vetner_organic-posts_April_4.jpg",
        "label": "Vetner organic-posts April 4",
        "filename": "Vetner/Vetner_organic-posts_April_4.jpg"
      },
      {
        "src": "/projects/Vetner/Vetner_organic-posts_April_5.jpg",
        "label": "Vetner organic-posts April 5",
        "filename": "Vetner/Vetner_organic-posts_April_5.jpg"
      },
      {
        "src": "/projects/Vetner/Vetner_organic-posts_April_6.jpg",
        "label": "Vetner organic-posts April 6",
        "filename": "Vetner/Vetner_organic-posts_April_6.jpg"
      },
      {
        "src": "/projects/Vetner/Vetner_organic-posts_April_7.jpg",
        "label": "Vetner organic-posts April 7",
        "filename": "Vetner/Vetner_organic-posts_April_7.jpg"
      },
      {
        "src": "/projects/Vetner/Vetner_organic-posts_April_8.jpg",
        "label": "Vetner organic-posts April 8",
        "filename": "Vetner/Vetner_organic-posts_April_8.jpg"
      }
    ],
    "videos": []
  }
]

export const mediaAudit = {
  "projects": 15,
  "images": 128,
  "videos": 13,
  "sourceOriginals": 6
} as const
